<?php

namespace xll\common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "setting".
 *
 * @property integer $id
 * @property string $taxonomy
 * @property string $code
 * @property string $value
 * @property integer $sort_order
 * @property integer $serialized
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $deleted_at
 */
class Setting extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'setting';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className()
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['taxonomy', 'code'], 'required'],
            [['value'], 'string'],
            [['sort_order', 'serialized', 'created_at', 'updated_at', 'deleted_at'], 'integer'],
            [['taxonomy', 'code'], 'string', 'max' => 64],
            [['code'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'taxonomy' => 'Taxonomy',
            'code' => 'Code',
            'value' => 'Value',
            'sort_order' => 'Sort Order',
            'serialized' => 'Serialized',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
        ];
    }

    public static function findByCode($code) {
        return static::findOne(['code' => $code]);
    }

    public function afterFind()
    {
        if($this->serialized) {
            $this->value = unserialize($this->value);
        }
        parent::afterFind(); // TODO: Change the autogenerated stub
    }
}
